devices([
  "iPhone 16 Pro Max",
  "iPhone 16"
])

languages([
  "en-US"
])

scheme("PromptVault")

output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
skip_open_summary(true)
stop_after_first_error(true)
concurrent_simulators(true)
reinstall_app(false)
